//
//  widget_faceraisedict.swift
//  snowie_learner
//
//  Created by yosuke-kurosu on 2020/12/28.
//  preflop adviser version cutoffは3bbopen, btnは2.5bbopenで固定

import Foundation

// face_raiseに関する辞書
var face_raise_dict = [
    "MP":["UTG":["raise":["AA", "AKs",       "AJs", "ATs",                 "A5s", "A4s", "A3s", "A2s",
                         "AKo", "KK", "KQs",
                                       "QQ",
                                              "JJ",
                                                    "76s",
                                                           "65s"],
                       "call":["AQs",
                                      "TT",
                                             "99"]]],
    
        "CUTOFF":["UTG":["raise":["AA", "AKs",        "AJs", "ATs",         "A5s", "A4s", "A3s", "A2s",
                                  "AKo", "KK", "KQs",
                                                "QQ",
                                                            "65s"],
                           "call":["AQs",
                                                      "KJs",
                                   "AQo",              "JJ",
                                                             "TT",
                                                                   "99",
                                                                         "88"]],
                  
                  "MP":["raise":["AA", "AKs",       "AJs", "ATs",             "A5s", "A4s", "A3s", "A2s",
                                 "AKo", "KK", "KQs",
                                 "AQo",        "QQ",
                                                    "76s",
                                                           "65s"],
                        "call":["AQs",
                                                     "KJs",
                                                     "QJs",
                                                      "JJ",
                                                            "TT",
                                                                  "99",
                                                                        "88"]]],
    
        "BUTTON":["UTG":["raise":["AA", "AKs",        "AJs", "ATs",             "A5s", "A4s", "A3s", "A2s",
                                  "AKo", "KK", "KQs", "KJs",
                                                "QQ",
                                                      "76s",
                                                             "65s",
                                                                    "54s"],
                         
                           "call":["AQs",
                                   "AQo",              "QJs",
                                                        "JJ", "JTs",
                                                               "TT",
                                                                     "99",
                                                                           "88",
                                                                                 "77"]],
                  
                  "MP":["raise":["AA", "AKs", "AQs",       "ATs", "A9s",           "A5s", "A4s", "A3s", "A2s",
                                 "AKo", "KK", "KQs", "KJs",
                                               "QQ",
                                                      "JJ",
                                                            "76s",
                                                                   "65s",
                                                                          "54s"],
                                   
                         "call":["AJs",
                                 "AQo",               "QJs",
                                                            "JTs",
                                                             "TT",
                                                                   "99",
                                                                         "88",
                                                                               "77"]],
                  
                  "CUTOFF":["raise":["AA", "AKs", "AQs",       "ATs", "A9s", "A8s",     "A5s", "A4s", "A3s", "A2s",
                                     "AKo", "KK", "KQs", "KJs",
                                                   "QQ",
                                                          "JJ",
                                                                "76s",
                                                                       "65s",
                                                                              "54s"],
                                       
                             "call":["AJs",
                                                                "KTs",
                                     "AQo",             "QJs",
                                     "AJo",                     "JTs",
                                                                 "TT",
                                                                       "99",
                                                                             "88",
                                                                                   "77"]]],

        "SB":["UTG":["raise":["AA", "AKs", "AQs", "AJs", "ATs", "A5s", "A4s",
                             "AKo", "KK", "KQs", "KJs",
                             "AQo",       "QQ",  "QJs",
                                                  "JJ",
                                                        "TT"],
                       "call":["99", "88", "77"]],
              
              "MP":["raise":["AA", "AKs", "AQs", "AJs", "ATs", "A5s", "A4s",
                             "AKo", "KK", "KQs", "KJs",
                             "AQo",        "QQ", "QJs",
                                                  "JJ", "JTs",
                                                         "TT",
                                                               "99",
                                                                     "88"],
                             "call":["77", "66"]],
              
              
              "CUTOFF":["raise":["AA", "AKs", "AQs", "AJs", "ATs", "A9s", "A5s", "A4s",
                                "AKo", "KK", "KQs", "KJs", "KTs",
                                "AQo", "KQo", "QQ", "QJs", "QTs",
                                "AJo",               "JJ", "JTs",
                                                            "TT", "T9s",
                                                                   "99",
                                                                         "88",
                                                                              "77",
                                                                                    "66",
                                                                                         "55"],
                        "call":[]],
              
              "BUTTON":["raise":["AA", "AKs", "AQs", "AJs", "ATs", "A9s", "A8s", "A7s", "A5s", "A4s",
                                 "AKo", "KK", "KQs", "KJs", "KTs", "K9s",
                                 "AQo", "KQo", "QQ", "QJo", "QTs", "Q9s",
                                 "AJo",        "QJo", "JJ", "JTs", "J9s",
                                                             "TT", "T9s",
                                                                    "99",
                                                                          "88",
                                                                                "77",
                                                                                      "66",
                                                                                            "55"],
                        "call":[]]],
    
        "BB":["UTG":["raise":["AA", "AKs", "AQs", "QQ"],
                       "call":[                     "AJs", "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s","A3s", "A2s",
                               "AKo",       "KQs",  "KJs", "KTs", "K9s",
                               "AQo", "KQo",        "QJs", "QTs", "Q9s",
                               "AJo",                "JJ", "JTs", "J9s",
                               "ATo",                       "TT", "T9s", "T8s",
                                                                   "99", "98s",
                                                                          "88", "87s", "86s",
                                                                                 "77", "76s", "75s",
                                                                                        "66", "65s", "64s",
                                                                                               "55", "54s", "53s",
                                                                                                      "44",
                                                                                                             "33",
                                                                                                                   "22"]],
              
              "MP":["raise":["AA", "AKs", "AQs", "AJs",
                             "AKo", "KK", "KQs",
                                           "QQ", "QJs",
                                                  "JJ",
                                                        "TT"],
                             "call":[                            "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s","A3s", "A2s",
                                                          "KJs", "KTs", "K9s", "K8s", "K7s",
                                     "AQo", "KQo",               "QTs", "Q9s",
                                     "AJo", "KJo", "QJo",        "JTs", "J9s",
                                     "ATo",                             "T9s", "T8s",
                                                                         "99", "98s", "97s",
                                                                                "88", "87s", "86s",
                                                                                       "77", "76s", "75s",
                                                                                              "66", "65s", "64s",
                                                                                                     "55", "54s", "53s",
                                                                                                            "44",
                                                                                                                   "33",
                                                                                                                         "22"]],

              
              "CUTOFF":["raise":["AA", "AKs", "AQs", "AJs", "ATs",
                                 "AKo", "KK", "KQs",
                                               "QQ", "QJs",
                                                      "JJ", "JTs",
                                                            "TT"],
                             "call":[                                   "A9s", "A8s", "A7s", "A6s", "A5s", "A4s","A3s", "A2s",
                                                          "KJs", "KTs", "K9s", "K8s", "K7s", "K6s",        "K4s",
                                     "AQo", "KQo",               "QTs", "Q9s", "Q8s",
                                     "AJo", "KJo", "QJo",               "J9s", "J8s",
                                     "ATo", "KTo",        "JTo",        "T9s", "T8s", "T7s",
                                                                         "99", "98s", "97s",
                                                                                "88", "87s", "86s",
                                                                                       "77", "76s", "75s",
                                                                                              "66", "65s", "64s",
                                                                                                     "55", "54s", "53s",
                                                                                                            "44", "43s",
                                                                                                                   "33",
                                                                                                                         "22"]],
              
              "BUTTON":["raise":["AA", "AKs", "AQs", "AJs", "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                                 "AKo", "KK", "KQs", "KJs", "KTs",
                                 "AQo",        "QQ", "QJs", "QTs",
                                                      "JJ", "JTs", "J9s",
                                                             "TT", "T9s",
                                                                    "99",
                                                                          "88",
                                                                                "77",
                                                                                     "66",
                                                                                           "55"],
                        
                             "call":[
                                                                        "K9s", "K8s", "K7s", "K6s", "K5s", "K4s", "K3s", "K2s",
                                "KQo",                                  "Q9s", "Q8s", "Q7s", "Q6s", "Q5s", "Q4s", "Q3s", "Q2s",
                                     "AJo", "KJo", "QJo",                      "J8s", "J7s", "J6s", "J5s", "J4s",
                                     "ATo", "KTo", "QTo", "JTo",               "T8s", "T7s", "T6s",
                                     "A9o", "K9o", "Q9o", "J9o",  "T9o",       "98s", "97s", "96s",
                                     "A8o",                              "98o",       "87s", "86s", "85s",
                                     "A7o",                                           "87o", "76s", "75s", "74s",
                                     "A6o",                                                         "65s", "64s", "63s",
                                     "A5o",                                                                "54s", "53s", "52s",
                                     "A4o",                                                                 "44", "43s", "42s",
                                     "A3o",                                                                        "33", "32s",
                                                                                                                         "22"]],
              
                   "SB":["raise":["AA", "AKs", "AQs", "AJs",                                                 "A2s",
                                 "AKo", "KK", "KQs", "KJs", "KTs", "K9s",                             "K3s", "K2s",
                                 "AQo", "KQo", "QQ", "QJs", "QTs",        "Q8s",
                                 "AJo",               "JJ", "JTs", "J9s",
                                                             "TT",
                                                                    
                                                                          
                                                                                
                                                                                     
                                 
                                  "A4o",
                                  "A3o",
                                  "A2o",                                                                             ],
                        
                             "call":[
                                                                               "K8s", "K7s", "K6s", "K5s", "K4s",
                                                                        "Q9s",        "Q7s", "Q6s", "Q5s", "Q4s", "Q3s", "Q2s",
                                            "KJo", "QJo",                      "J8s", "J7s", "J6s", "J5s", "J4s", "J3s", "J2s",
                                     "ATo", "KTo", "QTo", "JTo",        "T9s", "T8s", "T7s", "T6s", "T5s", "T4s", "T3s", "T2s",
                                     "A9o", "K9o", "Q9o", "J9o",  "T9o", "99", "98s", "97s", "96s", "95s", "94s", "93s", "92s",
                                     "A8o", "K8o", "Q8o", "J8o",  "T8o", "98o", "88", "87s", "86s", "85s", "84s", "83s", "82s",
                                     "A7o", "K7o", "Q7o",         "T7o", "97o", "87o", "77", "76s", "75s", "74s", "73s",
                                     "A6o",                                     "86o", "76o", "66", "65s", "64s", "63s", "62s",
                                     "A5o",                                                   "65o", "55", "54s", "53s", "52s",
                                     "A4o",                                                          "54o", "44", "43s", "42s",
                                     "A3o",                                                                        "33", "32s",
                                                                                                                         "22"]]]
    ]
